export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CHANGE_SHADOW_BLUR = "CHANGE_SHADOW_BLUR";
export const CHANGE_BORDER_RADIUS = "CHANGE_BORDER_RADIUS";
export const CHANGE_SHADOW_LENGTH = "CHANGE_SHADOW_LENGTH";
export const CHANGE_DARK_SHADOW_FACTOR = "CHANGE_DARK_SHADOW_FACTOR";
export const CHANGE_LIGHT_SHADOW_FACTOR = "CHANGE_LIGHT_SHADOW_FACTOR";





